# Runs maillec on CASE.maille and compares with CASE.ast (expected tree, exit 0) or CASE.err
# (expected error line, exit 1). The file name in the error is replaced by "input".
execute_process(COMMAND ${MAILLEC} ${CASE}.maille
  OUTPUT_VARIABLE out ERROR_VARIABLE err RESULT_VARIABLE code)
string(REPLACE "${CASE}.maille" "input" err "${err}")
# Windows writes text streams with CRLF, and git may check the expected files out with CRLF too.
string(REPLACE "\r\n" "\n" out "${out}")
string(REPLACE "\r\n" "\n" err "${err}")
if(EXISTS ${CASE}.ast)
  file(READ ${CASE}.ast expected)
  string(REPLACE "\r\n" "\n" expected "${expected}")
  if(NOT code EQUAL 0)
    message(FATAL_ERROR "expected a tree, got exit ${code}: ${err}")
  endif()
  if(NOT out STREQUAL expected)
    message(FATAL_ERROR "tree differs\n--- expected\n${expected}--- got\n${out}")
  endif()
elseif(EXISTS ${CASE}.err)
  file(READ ${CASE}.err expected)
  string(REPLACE "\r\n" "\n" expected "${expected}")
  if(NOT code EQUAL 1)
    message(FATAL_ERROR "expected an error (exit 1), got exit ${code}\n${out}")
  endif()
  if(NOT err STREQUAL expected)
    message(FATAL_ERROR "error differs\n--- expected\n${expected}--- got\n${err}")
  endif()
else()
  message(FATAL_ERROR "no ${CASE}.ast or ${CASE}.err")
endif()
