"""Writes the synthetic meshes shown by the portfolio viewer (projects/topologie/samples/).

Deterministic: running it again gives the same files. No external data.
"""
import math
import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "samples"


def write(name, comment, vertices, faces):
    lines = [f"# {comment}", "# Generated by scripts/make_samples.py, synthetic data."]
    lines += ["v %.6f %.6f %.6f" % v for v in vertices]
    lines += ["f " + " ".join(str(i + 1) for i in f) for f in faces]
    (OUT / name).write_text("\n".join(lines) + "\n", encoding="utf-8")


def torus(n=48, m=24, R=1.0, r=0.4):
    verts = []
    for i in range(n):
        u = 2 * math.pi * i / n
        for j in range(m):
            v = 2 * math.pi * j / m
            verts.append(((R + r * math.cos(v)) * math.cos(u), (R + r * math.cos(v)) * math.sin(u), r * math.sin(v)))
    idx = lambda i, j: (i % n) * m + (j % m)
    faces = [(idx(i, j), idx(i + 1, j), idx(i + 1, j + 1), idx(i, j + 1)) for i in range(n) for j in range(m)]
    return verts, faces


def icosphere(levels=3):
    t = (1 + math.sqrt(5)) / 2
    verts = [(-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0), (0, -1, t), (0, 1, t),
             (0, -1, -t), (0, 1, -t), (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1)]
    verts = [tuple(c / math.sqrt(1 + t * t) for c in v) for v in verts]
    faces = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11), (1, 5, 9), (5, 11, 4), (11, 10, 2),
             (10, 7, 6), (7, 1, 8), (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9), (4, 9, 5),
             (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)]
    for _ in range(levels):
        cache, new = {}, []

        def mid(a, b):
            key = (min(a, b), max(a, b))
            if key not in cache:
                p = [(x + y) / 2 for x, y in zip(verts[a], verts[b])]
                n = math.sqrt(sum(c * c for c in p))
                verts.append(tuple(c / n for c in p))
                cache[key] = len(verts) - 1
            return cache[key]

        for a, b, c in faces:
            ab, bc, ca = mid(a, b), mid(b, c), mid(c, a)
            new += [(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)]
        faces = new
    return verts, faces


def mobius(n=60, m=6, w=0.35):
    verts = []
    for i in range(n):
        u = 2 * math.pi * i / n
        for j in range(m + 1):
            s = w * (2 * j / m - 1)
            verts.append(((1 + s * math.cos(u / 2)) * math.cos(u), (1 + s * math.cos(u / 2)) * math.sin(u), s * math.sin(u / 2)))

    def idx(i, j):
        if i == n:  # half twist: the strip comes back upside down
            return m - j
        return i * (m + 1) + j

    faces = [(idx(i, j), idx(i + 1, j), idx(i + 1, j + 1), idx(i, j + 1)) for i in range(n) for j in range(m)]
    return verts, faces


def saddle(n=24):
    verts = [((2 * i / n - 1), (2 * j / n - 1), (2 * i / n - 1) ** 2 - (2 * j / n - 1) ** 2)
             for i in range(n + 1) for j in range(n + 1)]
    idx = lambda i, j: i * (n + 1) + j
    faces = [(idx(i, j), idx(i + 1, j), idx(i + 1, j + 1), idx(i, j + 1)) for i in range(n) for j in range(n)]
    return verts, faces


if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    write("torus.obj", "Torus R = 1, r = 0.4: positive curvature outside, negative inside, genus 1.", *torus())
    write("sphere.obj", "Icosphere, 3 subdivisions: nearly constant positive curvature, genus 0.", *icosphere())
    write("mobius.obj", "Moebius strip: one boundary loop, not orientable.", *mobius())
    write("saddle.obj", "Saddle z = x^2 - y^2: negative curvature, a disk with one boundary loop.", *saddle())
