/* Othello engine: the board as two 64-bit masks (one per colour), moves generated by bit shifts.
 * Squares are numbered 0 to 63 row by row: a1 = 0, h1 = 7, a8 = 56, h8 = 63, as in the usual notation
 * where rows 1 to 8 go from top to bottom and black (X) moves first from d5, e4 against d4, e5. */
#ifndef OTHELLO_H
#define OTHELLO_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum { OTH_BLACK = 0, OTH_WHITE = 1 };

typedef struct {
    uint64_t discs[2]; /* discs[OTH_BLACK], discs[OTH_WHITE] */
    int to_move;       /* OTH_BLACK or OTH_WHITE */
} oth_board;

/* The starting position, black to move. */
void oth_init(oth_board *b);

/* Legal moves of the side to move, as a mask of squares (0 when it must pass or the game is over). */
uint64_t oth_moves(const oth_board *b);

/* Discs flipped if the side to move plays on `square` (0 when the move is illegal). */
uint64_t oth_flips(const oth_board *b, int square);

/* Plays `square` for the side to move. Returns 0, or -1 if the move is illegal (board unchanged). */
int oth_play(oth_board *b, int square);

/* Passes. Returns 0, or -1 if the side to move has a legal move (passing is then forbidden). */
int oth_pass(oth_board *b);

/* 1 when neither side can move. */
int oth_game_over(const oth_board *b);

/* Number of discs of a colour. */
int oth_count(const oth_board *b, int colour);

/* Number of set bits of a mask. */
int oth_popcount(uint64_t mask);

/* "d3" -> 19; -1 if the name is not a square. */
int oth_square_from_name(const char *name);

/* 19 -> "d3" into buf (at least 3 bytes). */
void oth_square_name(int square, char *buf);

/* Leaves `depth` plies below the position, a forced pass counting as a ply and a finished game as a
 * leaf: the standard way to check a move generator against known counts. */
uint64_t oth_perft(const oth_board *b, int depth);

/* --- AI --- */

/* Static value of the position for the side to move (positive is good for it). */
int oth_evaluate(const oth_board *b);

/* Best move for the side to move by alpha-beta search to `depth` plies (ties go to the lowest square);
 * -1 if it must pass. `value`, if not NULL, receives the position's value. */
int oth_best_move(const oth_board *b, int depth, int *value);

/* Value of the position by negamax to `depth`, with (alphabeta = 1) or without alpha-beta pruning;
 * both must agree. `nodes`, if not NULL, counts the positions visited. */
int oth_search(const oth_board *b, int depth, int alphabeta, uint64_t *nodes);

#ifdef __cplusplus
}
#endif

#endif
