// Every text of the launcher, in French and English (a key missing in one language shows as is).
window.TEXTS = {
  fr: {
    title: 'Osmose',
    server: 'Serveur :',
    name: 'Nom de compte',
    password: 'Mot de passe',
    'sign-in': 'Se connecter',
    'signed-in': 'Connecté : {0}. Le jeu s\'ouvrira sur vos personnages.',
    game: 'Le jeu',
    installed: 'Version installée : {0}',
    'not-installed': 'Pas encore installé.',
    update: 'Mettre à jour',
    play: 'Jouer',
    checking: 'Comparaison avec le serveur…',
    progress: 'Fichier {0} sur {1} · {2} sur {3}',
    'up-to-date': 'Version {0} : à jour, rien à télécharger.',
    updated: 'Version {0} : {1} fichier(s) téléchargé(s) ({2}), {3} retiré(s).',
    started: 'Le jeu démarre.',
    note: 'Seuls les fichiers modifiés sont téléchargés ; chacun est vérifié (SHA-256), et un téléchargement coupé reprend où il s\'était arrêté.',
    'error.unreachable': 'Serveur injoignable : vérifiez l\'adresse, ou jouez hors ligne si le jeu est installé.',
    'error.wrong-password': 'Nom inconnu ou mot de passe faux.',
    'error.too-many-tries': 'Trop d\'essais : attendez une minute.',
    'error.server': 'Le serveur a refusé la demande.',
    'error.unreadable': 'Réponse illisible du serveur.',
    'error.corrupt': 'Un fichier reçu ne correspond pas à son empreinte : il sera téléchargé de nouveau.',
    'error.unsafe-path': 'Le serveur a envoyé un manifeste dangereux : mise à jour refusée.',
    'error.io': 'Erreur de fichier ou de lancement.',
  },
  en: {
    title: 'Osmose',
    server: 'Server:',
    name: 'Account name',
    password: 'Password',
    'sign-in': 'Sign in',
    'signed-in': 'Signed in: {0}. The game will open on your characters.',
    game: 'The game',
    installed: 'Installed version: {0}',
    'not-installed': 'Not installed yet.',
    update: 'Update',
    play: 'Play',
    checking: 'Comparing with the server…',
    progress: 'File {0} of {1} · {2} of {3}',
    'up-to-date': 'Version {0}: up to date, nothing to download.',
    updated: 'Version {0}: {1} file(s) downloaded ({2}), {3} removed.',
    started: 'The game is starting.',
    note: 'Only the changed files are downloaded; each one is checked (SHA-256), and a cut download resumes where it stopped.',
    'error.unreachable': 'Server unreachable: check the address, or play offline if the game is installed.',
    'error.wrong-password': 'Unknown name or wrong password.',
    'error.too-many-tries': 'Too many tries: wait a minute.',
    'error.server': 'The server refused the request.',
    'error.unreadable': 'Unreadable answer from the server.',
    'error.corrupt': 'A file received does not match its fingerprint: it will be downloaded again.',
    'error.unsafe-path': 'The server sent a dangerous manifest: update refused.',
    'error.io': 'File or start-up error.',
  },
};
