// Every text of the launcher, in French and English (a key missing in one language shows as is).
window.TEXTS = {
  fr: {
    name: 'Nom de compte',
    password: 'Mot de passe',
    confirm: 'Confirmer le mot de passe',
    'password-saved': 'Mot de passe mémorisé',
    'remember-name': 'Mémoriser le nom de compte',
    'remember-password': 'Mémoriser le mot de passe',
    'sign-in': 'Se connecter',
    'sign-up': 'Créer le compte',
    created: 'Compte {0} créé : connectez-vous.',
    'to-sign-up': 'Pas encore de compte ? En créer un',
    'to-sign-in': "J'ai déjà un compte",
    checking: 'Recherche de mise à jour…',
    progress: 'Mise à jour : fichier {0} sur {1} · {2} sur {3}',
    'up-to-date': 'Jeu à jour (version {0}).',
    updated: 'Jeu mis à jour (version {0}, {1}).',
    waiting: 'Connecté : fin de la mise à jour avant de lancer le jeu…',
    started: 'Le jeu démarre. Bonne partie !',
    'not-installed': "Le jeu n'a pas pu être installé : vérifiez la connexion et réessayez.",
    'error.short': 'Le mot de passe compte au moins 10 caractères.',
    'error.mismatch': 'Les deux mots de passe ne sont pas identiques.',
    'error.fill-in': 'Indiquez un nom de compte et un mot de passe.',
    'error.unreachable': 'Serveur injoignable : vérifiez votre connexion.',
    'error.wrong-password': 'Nom inconnu ou mot de passe faux.',
    'error.name-taken': 'Ce nom de compte est déjà pris.',
    'error.invalid': 'Nom de compte : 3 à 20 lettres sans accent, chiffres, « - » ou « _ » ; mot de passe : 10 à 128 caractères.',
    'error.missing-password': 'Indiquez le mot de passe : aucun n\'est mémorisé pour ce compte.',
    'error.secrets': 'Connecté, mais le mot de passe n\'a pas pu être mémorisé sur ce système.',
    'error.too-many-tries': "Trop d'essais : attendez une minute.",
    'error.server': 'Le serveur a refusé la demande.',
    'error.unreadable': 'Réponse illisible du serveur.',
    'error.corrupt': 'Un fichier reçu ne correspond pas à son empreinte : il sera téléchargé de nouveau.',
    'error.unsafe-path': 'Le serveur a envoyé un manifeste dangereux : mise à jour refusée.',
    'error.io': 'Erreur de fichier ou de lancement.',
  },
  en: {
    name: 'Account name',
    password: 'Password',
    confirm: 'Confirm the password',
    'password-saved': 'Password remembered',
    'remember-name': 'Remember the account name',
    'remember-password': 'Remember the password',
    'sign-in': 'Sign in',
    'sign-up': 'Create the account',
    created: 'Account {0} created: sign in.',
    'to-sign-up': 'No account yet? Create one',
    'to-sign-in': 'I already have an account',
    checking: 'Looking for an update…',
    progress: 'Updating: file {0} of {1} · {2} of {3}',
    'up-to-date': 'Game up to date (version {0}).',
    updated: 'Game updated (version {0}, {1}).',
    waiting: 'Signed in: finishing the update before starting the game…',
    started: 'The game is starting. Have fun!',
    'not-installed': 'The game could not be installed: check the connection and try again.',
    'error.short': 'A password has at least 10 characters.',
    'error.mismatch': 'The two passwords differ.',
    'error.fill-in': 'Enter an account name and a password.',
    'error.unreachable': 'Server unreachable: check your connection.',
    'error.wrong-password': 'Unknown name or wrong password.',
    'error.name-taken': 'This account name is already taken.',
    'error.invalid': 'Account name: 3 to 20 unaccented letters, digits, "-" or "_"; password: 10 to 128 characters.',
    'error.missing-password': 'Enter the password: none is remembered for this account.',
    'error.secrets': 'Signed in, but the password could not be remembered on this system.',
    'error.too-many-tries': 'Too many tries: wait a minute.',
    'error.server': 'The server refused the request.',
    'error.unreadable': 'Unreadable answer from the server.',
    'error.corrupt': 'A file received does not match its fingerprint: it will be downloaded again.',
    'error.unsafe-path': 'The server sent a dangerous manifest: update refused.',
    'error.io': 'File or start-up error.',
  },
};
