// Measures the React and Angular dashboards side by side (D44) and writes data/comparison.json, read by
// the site for the project page. Run from the repository root, both projects installed (npm ci in each):
//   node projects/angular/scripts/compare.mjs
// Build times are medians of three builds on this machine; everything else does not depend on it.
import { execFileSync, execSync } from 'node:child_process';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { cpus, tmpdir } from 'node:os';
import { join, relative } from 'node:path';
import { gzipSync } from 'node:zlib';

const ROOT = join(import.meta.dirname, '../../..');
const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';

function files(dir, keep = () => true) {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? files(p, keep) : keep(p) ? [p] : [];
  });
}

const median = (v) => [...v].sort((a, b) => a - b)[Math.floor(v.length / 2)];

/** Raw and gzip-compressed bytes of the JavaScript and CSS, all of it and what the first page loads. */
function bundle(dist, initial) {
  const assets = files(dist, (f) => /\.(js|css)$/.test(f));
  const size = (list) => list.reduce((acc, f) => {
    const bytes = readFileSync(f);
    return { raw: acc.raw + bytes.length, gzip: acc.gzip + gzipSync(bytes, { level: 9 }).length };
  }, { raw: 0, gzip: 0 });
  const html = readFileSync(join(dist, 'index.html'), 'utf8');
  // What index.html loads by itself: its scripts and stylesheets (not the chunks loaded on demand).
  const first = assets.filter((f) => html.includes(initial(relative(dist, f).split('\\').join('/'))));
  return { total: size(assets), initial: size(first), files: assets.length };
}

/** Non-blank lines, by extension. */
function lines(list) {
  return list.reduce((n, f) => n + readFileSync(f, 'utf8').split('\n').filter((l) => l.trim()).length, 0);
}

function buildTime(dir) {
  const times = [];
  for (let i = 0; i < 3; i++) {
    const start = process.hrtime.bigint();
    execFileSync(npm, ['run', 'build'], { cwd: dir, stdio: 'pipe', shell: process.platform === 'win32' });
    times.push(Number(process.hrtime.bigint() - start) / 1e6);
  }
  return Math.round(median(times));
}

/** Packages npm installed (node_modules, nested ones included), from the lockfile. */
function packages(dir) {
  const lock = JSON.parse(readFileSync(join(dir, 'package-lock.json'), 'utf8'));
  return Object.keys(lock.packages).filter((k) => k.includes('node_modules/')).length;
}

const react = join(ROOT, 'projects/react');
const angular = join(ROOT, 'projects/angular');
// Code both dashboards use: the API's types, the views' computations, chart scales, texts, styles.
const SHARED = ['src/api.ts', 'src/model.ts', 'src/charts/scale.ts', 'src/i18n.ts', 'src/styles.css'].map((f) => join(react, f));
// The React dashboard's own code for the same two views and their frame (its 3D viewer and sprints view
// have no Angular counterpart and are left out).
const REACT_OWN = ['src/main.tsx', 'src/App.tsx', 'src/charts/BarChart.tsx', 'src/charts/LineChart.tsx', 'src/views/ProjectsView.tsx', 'src/views/ResultsView.tsx']
  .map((f) => join(react, f));
const ANGULAR_OWN = files(join(angular, 'src'), (f) => /\.(ts|html|css)$/.test(f) && !f.endsWith('styles.css') && !f.endsWith('shared.ts'));

const tests = (dir, args) => {
  const out = execSync(`${npm} ${args}`, { cwd: dir, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  return out;
};
// Vitest writes its JSON report to a file; Jest prints it.
const report = join(tmpdir(), `vitest-${process.pid}.json`);
tests(react, `exec -- vitest run --reporter=json --outputFile=${report}`);
const vitest = JSON.parse(readFileSync(report, 'utf8')).numTotalTests;
const jestRun = JSON.parse(tests(angular, 'exec -- jest --json --silent')).numTotalTests;

const result = {
  machine: { cpu: cpus()[0]?.model.trim() ?? 'unknown', node: process.version, date: new Date().toISOString().slice(0, 10) },
  react: {
    version: JSON.parse(readFileSync(join(react, 'node_modules/react/package.json'), 'utf8')).version,
    buildMs: buildTime(react),
    bundle: bundle(join(react, 'dist'), (f) => f),
    lines: lines(REACT_OWN),
    // Unit and integration tests (Vitest); the end-to-end ones are generated by loops, counted elsewhere.
    tests: vitest,
    packages: packages(react),
  },
  angular: {
    version: JSON.parse(readFileSync(join(angular, 'node_modules/@angular/core/package.json'), 'utf8')).version,
    buildMs: buildTime(angular),
    bundle: bundle(join(angular, 'dist'), (f) => f),
    lines: lines(ANGULAR_OWN),
    tests: jestRun,
    packages: packages(angular),
  },
  shared: { lines: lines(SHARED), files: SHARED.map((f) => relative(ROOT, f).split('\\').join('/')) },
};
writeFileSync(join(angular, 'data/comparison.json'), `${JSON.stringify(result, null, 2)}\n`);
console.log(JSON.stringify(result, null, 2));
