<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>rogue</AssemblyName>
    <RootNamespace>Rogue.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Rogue.Client/Rogue.Client.csproj" />
    <InternalsVisibleTo Include="Rogue.Cli.Tests" />
  </ItemGroup>
</Project>
